---
- name: Add mariadb repository
  yum_repository:
    name: mariadb
    description: mariadb repository at http://downloads.mariadb.org/mariadb/repositories/
    baseurl: "http://yum.mariadb.org/10.0/centos7-amd64"
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes
  become: yes

- name: Install required packages
  yum:
    name:
      # Compression utilities
      - zstd
      # Download utilities
      - curl # for downloads
      - wget # for downloads
      # Documentation utilities
      - doxygen # for building documentation
      - graphviz # for building documentation
      - texlive-latex # for building documentation
      - texlive-latex-bin # for building documentation
      - texlive-dvips # for building documentation
      - texlive-dvips-bin # for building documentation
      - texlive-cm # for building documentation
      - bison # Qt build dependency
      - flex # Qt build dependency
      - gperf # Qt build dependency
      - MariaDB
      - xorg-x11-utils # for xdpyinfo
      - glx-utils # for glxinfo
      - mesa-dri-drivers # for OpenGL to work inside XDummy
    state: latest
    use_backend: yum
  become: yes

- name: Install JFrog cli
  get_url:
    url: https://api.bintray.com/content/jfrog/jfrog-cli-go/$latest/jfrog-cli-linux-386/jfrog?bt_package=jfrog-cli-linux-386
    dest: /usr/bin/jfrog
    mode: "u=rwx,g=rx,o=rx"
  become: yes

- name: Install conan
  pip:
    name: conan
    state: latest
    executable: pip3
    extra_args: "--user"
