---
- name: Add mariadb repository
  ansible.builtin.yum_repository:
    name: mariadb
    description: mariadb repository at http://downloads.mariadb.org/mariadb/repositories/
    baseurl: "http://yum.mariadb.org/10.6/centos7-amd64"
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes
  become: true

- name: Install required packages
  ansible.builtin.yum:
    name:
      # Compression utilities
      - zstd
      # Download utilities
      - curl # for downloads
      - wget # for downloads
      - jq
      - dos2unix # used by update_codens.sh
      # Documentation utilities
      - doxygen # for building documentation
      - graphviz # for building documentation
      - texlive-latex # for building documentation
      - texlive-latex-bin # for building documentation
      - texlive-dvips # for building documentation
      - texlive-dvips-bin # for building documentation
      - texlive-cm # for building documentation
      - texlive-collection-fontsrecommended # for building documentation
      - ghostscript # for building documentation (doxygen is becoming a bit of a pain...)
      # - texlive-collection-fontsextra # for building documentation
      # - texlive-collection-mathextra # for building documentation
      - rsync # for syncing documentation
      - bison # Qt build dependency
      - flex # Qt build dependency
      - gperf # Qt build dependency
      - diffutils # for diffing large results in conquest tests
      - MariaDB
      - xorg-x11-utils # for xdpyinfo
      - glx-utils # for glxinfo
      - mesa-dri-drivers # for OpenGL to work inside XDummy
    state: present
    use_backend: yum
  become: true

- name: Install JFrog cli
  ansible.builtin.get_url:
    url: https://releases.jfrog.io/artifactory/jfrog-cli/v2/[RELEASE]/jfrog-cli-linux-amd64/jfrog
    dest: /usr/bin/jfrog
    mode: "u=rwx,g=rx,o=rx"
  become: true

- name: Install conan
  become: yes
  become_user: vagrant
  become_method: su
  become_flags: '--login'
  ansible.builtin.pip:
    name: conan=={{ conan_version }}
    state: present
    executable: pip3
    extra_args: "--user"
