---
- name: Ensure user can deploy manpages
  ansible.builtin.file:
    path: /usr/local/share/man/man8
    state: directory
    recurse: yes
    owner: "{{ ansible_user }}"
  become: true

- name: Install required tools
  community.general.homebrew:
    name:
      # Compression utilities
      - xz # efficient compression
      # Download utilities
      - wget # for downloads, curl is part of the system
      - jq
      - diffutils # for diffing large results in conquest tests
      # Documentation utilities
      - doxygen # for building documentation
      - graphviz # for building documentation
      # Artifactory
      - jfrog-cli # for uploading to artifactory
      # Python utilities
      - pyenv # In order to install multiple versions of python, as homebrew only brings in 'the latest'
      - conan
      # The server is required to run csd_mariadb_databaselib testsuite
      - mariadb
    state: present
