---
- name: Get remote username
  ansible.builtin.set_fact:
    remote_username: "{{ ansible_user_id }}"

- name: Ensure user can deploy manpages
  ansible.builtin.file:
    path: /usr/local/share/man/man8
    state: directory
    recurse: yes
    owner: "{{ remote_username }}"
  become: true

- name: Install Homebrew + tools
  ansible.builtin.include_role:
    name: geerlingguy.mac.homebrew

- name: Ensure necessary homebrew packages are installed
  community.general.homebrew:
    name:
      - xz
      - gnu-tar # For gtar
      # Download utilities
      - wget # for downloads, curl is part of the system
      - jq
      - diffutils # for diffing large results in conquest tests
      # Documentation utilities
      - doxygen # for building documentation
      - graphviz # for building documentation
      # Python utilities
      - pyenv # In order to install multiple versions of python, as homebrew only brings in 'the latest'
      - pipx
      - python-packaging
      # To set conquest app icon
      - fileicon
    state: present
  when: not cpp_buildmachine

# Install Specfic conan version
- name: Link pipx
  ansible.builtin.command: pipx ensurepath
  environment:
    PATH: "/opt/homebrew/bin:/usr/local/bin:{{ ansible_env.PATH }}"

- name: install conan 2.24
  ansible.builtin.command: pipx install conan==2.24
  environment:
    PATH: "/opt/homebrew/bin:/usr/local/bin:{{ ansible_env.PATH }}"
