---
- name: Install required tools
  homebrew:
    name:
      # Compression utilities
      - xz # efficient compression
      # Download utilities
      - wget # for downloads, curl is part of the system
      - jq
      # Documentation utilities
      - doxygen # for building documentation
      - graphviz # for building documentation
      # Artifactory
      - jfrog-cli # for uploading to artifactory
      # Build utilities
      - ninja # for fast builds
      - cmake
      # Python utilities
      - swig
      - pyenv # In order to install multiple versions of python, as homebrew only brings in 'the latest'
      - conan
    state: present
