---
- name: Set up package managers for required tools
  ansible.builtin.include_role:
    name: ccdc.package_manager_configuration

- name: Set up required development tools
  ansible.builtin.include_tasks: "{{ taskfile }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_system }}.yml"
  loop_control:
    loop_var: taskfile
